StockMarket/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views

from .views import logout_view, signup_view

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', views.login, {'template_name': 'login.html'}),
    url(r'^logout/$', logout_view),
    url(r'^signup/$', signup_view),
    url(r'^', include('dashboard.urls')),
]

dashboard/urls.py
from django.conf.urls import include, url

from .views import (
	dashboard_view,
	profile_view,
	refresh_view,
	search_view,
)

urlpatterns = [
	url(r'^profile$', profile_view),
	url(r'^refresh=(?P<series>[0-9]{1})$', refresh_view),
	url(r'^search=(?P<query>[\w-]+)/$', search_view),
	url(r'^$', dashboard_view),
]

dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from datetime import datetime

class Search(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	query = models.CharField(max_length=255)
	timestamp = models.DateTimeField(default=datetime.now)

	class Meta:
		verbose_name_plural = "Searches"

	def __str__(self):
		return self.query

class Profile(models.Model):
	REFRESH_RATES = (
		(60000, '1 min'),
		(180000, '3 min'),
		(600000, '10 min'),
		(1800000, '30 min'),
	)
	user = models.OneToOneField(
		User,
		on_delete=models.CASCADE,
		primary_key=True,
	)
	refresh_time = models.IntegerField(
		choices=REFRESH_RATES,
		default=60000,
	)


class Stock(models.Model):
	name = models.CharField(max_length=255)

	def __str__(self):
		return self.name

class StockDailyFive(models.Model):
	name = models.ForeignKey(Stock, on_delete=models.CASCADE)
	opening = models.DecimalField(max_digits=20,decimal_places=8)
	closing = models.DecimalField(max_digits=20,decimal_places=8)
	high = models.DecimalField(max_digits=20,decimal_places=8)
	low = models.DecimalField(max_digits=20,decimal_places=8)
	volume = models.DecimalField(max_digits=20,decimal_places=8)
	timestamp = models.DateTimeField()

	def __str__(self):
		return '%s %s' % (self.name.name, self.timestamp)

class StockDailyFifteen(models.Model):
	name = models.ForeignKey(Stock, on_delete=models.CASCADE)
	opening = models.DecimalField(max_digits=20,decimal_places=8)
	closing = models.DecimalField(max_digits=20,decimal_places=8)
	high = models.DecimalField(max_digits=20,decimal_places=8)
	low = models.DecimalField(max_digits=20,decimal_places=8)
	volume = models.DecimalField(max_digits=20,decimal_places=8)
	timestamp = models.DateTimeField()

	def __str__(self):
		return '%s %s' % (self.name.name, self.timestamp)

class StockDailyThirty(models.Model):
	name = models.ForeignKey(Stock, on_delete=models.CASCADE)
	opening = models.DecimalField(max_digits=20,decimal_places=8)
	closing = models.DecimalField(max_digits=20,decimal_places=8)
	high = models.DecimalField(max_digits=20,decimal_places=8)
	low = models.DecimalField(max_digits=20,decimal_places=8)
	volume = models.DecimalField(max_digits=20,decimal_places=8)
	timestamp = models.DateTimeField()

	class Meta:
		verbose_name_plural = "Stock daily thirties"

	def __str__(self):
		return '%s %s' % (self.name.name, self.timestamp)

class StockWeekly(models.Model):
	name = models.ForeignKey(Stock, on_delete=models.CASCADE)
	opening = models.DecimalField(max_digits=20,decimal_places=8)
	closing = models.DecimalField(max_digits=20,decimal_places=8)
	high = models.DecimalField(max_digits=20,decimal_places=8)
	low = models.DecimalField(max_digits=20,decimal_places=8)
	volume = models.DecimalField(max_digits=20,decimal_places=8)
	timestamp = models.DateTimeField()

	class Meta:
		verbose_name_plural = "Stock weekly"

	def __str__(self):
		return '%s %s' % (self.name.name, self.timestamp)

class StockMonthly(models.Model):
	name = models.ForeignKey(Stock, on_delete=models.CASCADE)
	opening = models.DecimalField(max_digits=20,decimal_places=8)
	closing = models.DecimalField(max_digits=20,decimal_places=8)
	high = models.DecimalField(max_digits=20,decimal_places=8)
	low = models.DecimalField(max_digits=20,decimal_places=8)
	volume = models.DecimalField(max_digits=20,decimal_places=8)
	timestamp = models.DateTimeField()

	class Meta:
		verbose_name_plural = "Stock monthly"

	def __str__(self):
		return '%s %s' % (self.name.name, self.timestamp)

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
	if created:
		profile = Profile(user=instance)
		profile.save()

dashboard/forms.py
from django import forms

from .models import Profile
from .utils import ATTRIBUTES, TIME_INTERVALS, STOCKS

class UserSettingsForm(forms.ModelForm):
	class Meta:
		model = Profile
		fields = ('refresh_time', )

class StockFilterForm(forms.Form):
	interval = forms.TypedChoiceField(coerce=int, choices=TIME_INTERVALS)
	stock = forms.ChoiceField(choices=STOCKS)
	attribute = forms.ChoiceField(choices=ATTRIBUTES)

StockMarket/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

@login_required
def logout_view(request):
    logout(request)
    return redirect('/')

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import StockFilterForm, UserSettingsForm
from .models import Profile, Search
from .utils import (
	fetch_data,
	fetch_news,
	update_database,
	TIME_INTERVALS,
	FUNCTIONS,
)

def dashboard_view(request):
	data = {}
	if request.user.is_authenticated():
		searches = Search.objects.filter(user=request.user).order_by('-timestamp')
		for ind, search in enumerate(searches):
			data[ind] = search.query
		value = Profile.objects.filter(user=request.user).values('refresh_time')[0]['refresh_time']
	else:
		value = 60000
	if request.method == 'POST':
		form = StockFilterForm(request.POST)
		if form.is_valid():
			stock = request.POST.get('stock', '')
			interval = int(request.POST.get('interval', ''))
			attribute = request.POST.get('attribute', '')
	else:
		form = StockFilterForm()
		stock = 'AAPL'
		interval = 0
		attribute = 'opening'
	stats = fetch_data(stock, interval)
	data = json.dumps(data)
	return render(request, 'dashboard.html', {
		'data': data,
		'stats': stats,
		'val': value,
		'form': form,
		'series': interval,
		'attr': attribute,
	})

@login_required(login_url='/login')
def profile_view(request):
	if request.method == 'POST':
		form = UserSettingsForm(request.POST)
		if form.is_valid():
			refresh_time = request.POST.get('refresh_time', '')
			Profile.objects.filter(user=request.user).update(refresh_time=refresh_time)
			value = refresh_time
	else:
		value = Profile.objects.filter(user=request.user).values('refresh_time')[0]['refresh_time']
	form = UserSettingsForm()
	return render(request, 'profile.html', { 'form': form, 'val': value })

def refresh_view(request, series):
	update_database(int(series))
	return redirect('/')

def search_view(request, query):
	if request.user.is_authenticated():
		user = request.user
		search = Search(user=user, query=query)
		search.save()
	news = fetch_news(query)
	return render(request, 'search.html', { 'query': query, 'news': news })

dashboard/templates/dashboard.html
{% extends "base.html" %}

{% block title %}
<title>Stock Market Dashboard</title>
{% endblock %}

{% block content %}
<nav id="search-bar" class="indigo darken-4">
	<div class="nav-wrapper">
		<form>
			<div class="input-field" id="input-parent">
				<i id="search-prefix-tag" class="material-icons prefix" title="Hit Enter to Search">search</i>
				<input id="search" class="dropdown-trigger" placeholder="Stock News Updates" title="Hit Enter to Search" data-target='dropdown1' maxlength="255">
				<i class="material-icons suffix" title="Clear text">close</i>
			</div>
		</form>
	</div>
</nav>
<div class="container">
	<h3 class="indigo-text text-darken-4">Stock Update<i id="refresh" class="material-icons refresh-btn right">refresh</i></h3>
</div>
<div class="container">
	<form action="/" method="post">
		{% csrf_token %}
		{{ form }}
		<br><br>
		<input class="btn indigo darken-4" type="submit" value="Filter">
	</form>
</div>
<div class="row">
	<div class="col s4 m4 l4 push-s4 push-m4 push-l4">
		<div id="graph-value">
			<table>
				<tr>
					<th>Stock (Y)</th>
					<th>Timestamp (X)</th>
				</tr>
				<tr>
					<td id="x-val"><i>hover over graph</i></td>
					<td id="y-val"><i>hover over graph</i></td>
				</tr>
			</table>
		</div>
	</div>
</div>
<div class="row simple-row">
	<div class="col s12 m12 l12 blob-parent first-row">
		<div class="col s8 m8 l8 push-s2 push-m2 push-l2 blob" id="blob-first">
			<svg viewBox="0 0 3000 1800" class="inner-blob" id="stocksvg">
				<line x1="100" y1="50" x2="100" y2="1700" />
				<line x1="100" y1="50" x2="80" y2="70" />
				<line x1="100" y1="50" x2="120" y2="70" />
				<line x1="100" y1="1700" x2="2950" y2="1700" />
				<line x1="2950" y1="1700" x2="2930" y2="1680" />
				<line x1="2950" y1="1700" x2="2930" y2="1720" />
				<text x="70" y="1730">O</text>
			</svg>
		</div>
	</div>
</div>
<ul id='dropdown1' class='dropdown-content'></ul>
{% endblock %}

{% block scripts %}
<script src="https://d3js.org/d3.v5.min.js"></script>
<script>
	var stats = `{{ stats }}`;
	stats = stats.replaceAll('&quot;', '"').replaceAll('u"', '"');
	var data = `{{ data }}`;
	var option = `{{ val }}`;
	data = data.replaceAll('&quot;', '"').replaceAll('-', ' ');
	var series = `{{ series }}`;
	var attribute = `{{ attr }}`;
	$(document).ready(function() {
		changeDropdown(data);
		createSVG(stats, attribute);
		$('input#search').bind('keydown', function(e) {
			if (e.which === 13) {
				var query = $("#search").val().replaceAll(' ', '-');
				window.location.href = 'http://127.0.0.1:8000/' + `search=${query}/`;
				e.preventDefault();
			}
		});
		$('i.suffix').bind('click', function() {
			document.querySelector('input#search')['value'] = '';
			document.querySelector('input#search').focus();
		});
		$('#search-prefix-tag').bind('click', function() {
			document.querySelector('input#search').focus();
		});
		var el = document.querySelector('i#refresh');
		el.onclick = function() {
			document.querySelector('body').innerHTML = `
				<div class="loader-wrapper">
					<div class="loader"></div>
				</div>
			`;
			window.location.assign(window.location.href + 'refresh=' + series);
		};
		setTimeout(function() {
			$('i#refresh').click();
		}, option);
	});
</script>
{% endblock %}

dashboard/templates/profile.html
{% extends "base.html" %}

{% block title %}
<title>{{ user.username }} | Profile</title>
{% endblock %}

{% block content %}
<div class="container center">
	<i class="material-icons person-icon">account_circle</i>
	<h1>{{ user.username }}</h1>
</div>
<div class="container padded-rounded-section">
	<form action="/profile" method="post">
		{% csrf_token %}
		{{ form }}
		<br><br>
		<input class="btn indigo darken-4" type="submit" value="Save">
	</form>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
	var option = `{{ val }}`;
	option = parseInt(option);
	console.log(option);
	$(document).ready(function() {
		$('select#id_refresh_time').val(option);
	});
</script>
{% endblock %}

dashboard/templates/search.html
{% extends "base.html" %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block content %}
<div class="container">
	<h2>News result for {{ query }}</h2>
</div>
<div class="row">
	{% for article in news %}
		<div class="col s12 m6">
			<div class="card">
				<div class="card-content">
					<span class="card-title">{{ article.title }}</span>
					<span class="card-subtitle-1">By {{ article.author }} at {{ article.publishedAt }}</span>
					<h6>{{ article.description }}</h6>
					<p>{{ article.content }}</p>
				</div>
				<div class="card-action">
					<a target="_blank" href="{{ article.url }}"><i class="material-icons new-icon">open_in_new</i>&nbsp;&nbsp;URL</a>
				</div>
			</div>
		</div>
	{% endfor %}
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	{% block title %}
	{% endblock %}

	<!-- CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">	
	{% block stylesheets %}
	{% endblock %}
</head>
<body>
	<nav>
		<div class="nav-wrapper indigo darken-4">
			<a class="brand-logo" href="/">Stock Market Dashboard</a>
			<ul id="nav-mobile" class="right hide-on-med-and-down">
				{% if user.is_authenticated %}
				<li><a href="/profile" class="profile waves-effect waves-light btn white indigo-text text-darken-4">{{user.username}}</a></li>
				<li><a href="/">Home</a></li>
				<li><a href="/logout/" class="waves-effect waves-light btn red">Logout</a></li>
				{% else %}
				<li><a href="/">Home</a></li>
				<li><a href="/login/">Login</a></li>
				<li><a href="/signup/">Register</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>

	{% block content %}
	{% endblock %}
	
	<!-- Scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="{% static 'js/app.js' %}"></script>
	{% block scripts %}
	{% endblock %}
</body>
</html>

templates/login.html
{% extends "base.html" %}

{% block title %}
<title>Login</title>
{% endblock %}

{% block content %}
<div class="row auth-row">
    <div class="col s2 push-s5">
        <form method="POST">
            {% csrf_token %}
            <div>
                <label>Username</label>
                <input type="text" name="username" />
            </div>
            <div>
                <label>Password</label>
                <input type="password" name="password" />
            </div>
            <div class="center row"><button class="col s12 waves-effect waves-light btn indigo darken-4" type="submit">Login</button></div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col s6 m6 l6" id="blob-0"></div>
</div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}

{% block title %}
<title>Register</title>
{% endblock %}

{% block content %}
<div class="row auth-row">
	<div class="col s4 push-s4">
		<form method="POST">
			{% csrf_token %} {{ form.as_p }}
			<div class="center"><button class="waves-effect waves-light btn btn-large indigo darken-4" type="submit">register</button></div>
		</form>
	</div>
</div>
{% endblock %}